<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Localization/CustomGitHubRepository.cs" Link="CustomGitHubRepository.cs" />
    <Compile Include="../../Update/CustomUpdateInfo.cs" Link="CustomUpdateInfo.cs" />
    <Compile Include="../../Settings/AppSettings.cs" Link="AppSettings.cs" />
    <Compile Include="../../Settings/LocalizationSettings.cs" Link="LocalizationSettings.cs" />
    <ProjectReference Include="../../../SCToolsLib/SCToolsLib.csproj" />
  </ItemGroup>
</Project>
