<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Runner.cs" />
    <Compile Include="../../Update/CustomApplicationUpdater.cs" Link="CustomApplicationUpdater.cs" />
    <Compile Include="../../Update/CustomPackageVerifier.cs" Link="CustomPackageVerifier.cs" />
    <Compile Include="../../Update/ReleaseVersion.cs" Link="ReleaseVersion.cs" />
    <Compile Include="../../Update/UpdateProcessHelper.cs" Link="UpdateProcessHelper.cs" />
    <Compile Include="../../Update/ApplicationUpdateRepository.cs" Link="ApplicationUpdateRepository.cs" />
    <ProjectReference Include="../../../SCToolsLib/SCToolsLib.csproj" />
  </ItemGroup>
</Project>
