//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCTool_Redesigned.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCTool_Redesigned.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static byte[] GmarketSansBold {
            get {
                object obj = ResourceManager.GetObject("GmarketSansBold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static byte[] GmarketSansMedium {
            get {
                object obj = ResourceManager.GetObject("GmarketSansMedium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   The location you specified is not the location where Star Citizen is installed. Find and select the &quot;StarCitizen&quot; folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_Decs_NotGameFolder {
            get {
                return ResourceManager.GetString("MSG_Decs_NotGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the localization to apply to the game.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_Decs_SelectLocalization {
            get {
                return ResourceManager.GetString("MSG_Decs_SelectLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the Star Citizen game folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_Title_NotGameFolder {
            get {
                return ResourceManager.GetString("MSG_Title_NotGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select localization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_Title_SelectLocalization {
            get {
                return ResourceManager.GetString("MSG_Title_SelectLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find and select the same folder as &quot;StarCitizen&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_Title_SelectStarCitizenDirectory {
            get {
                return ResourceManager.GetString("MSG_Title_SelectStarCitizenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static byte[] SCDream3 {
            get {
                object obj = ResourceManager.GetObject("SCDream3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static byte[] SCDream5 {
            get {
                object obj = ResourceManager.GetObject("SCDream5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static byte[] SCDream9 {
            get {
                object obj = ResourceManager.GetObject("SCDream9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_Cancel {
            get {
                return ResourceManager.GetString("UI_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable Localization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_DisableLocalization {
            get {
                return ResourceManager.GetString("UI_Button_DisableLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_Edit {
            get {
                return ResourceManager.GetString("UI_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_Install {
            get {
                return ResourceManager.GetString("UI_Button_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install Localization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_InstallLocalization {
            get {
                return ResourceManager.GetString("UI_Button_InstallLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_Next {
            get {
                return ResourceManager.GetString("UI_Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_No {
            get {
                return ResourceManager.GetString("UI_Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prev과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_Previous {
            get {
                return ResourceManager.GetString("UI_Button_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_Quit {
            get {
                return ResourceManager.GetString("UI_Button_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_Refresh {
            get {
                return ResourceManager.GetString("UI_Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Localization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_RemoveLocalization {
            get {
                return ResourceManager.GetString("UI_Button_RemoveLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_Save {
            get {
                return ResourceManager.GetString("UI_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_Select {
            get {
                return ResourceManager.GetString("UI_Button_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_SelectLang {
            get {
                return ResourceManager.GetString("UI_Button_SelectLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Button_Yes {
            get {
                return ResourceManager.GetString("UI_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **Loading...**과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Desc_BringingMarkdown {
            get {
                return ResourceManager.GetString("UI_Desc_BringingMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking Updates...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Desc_CheckingUpdate {
            get {
                return ResourceManager.GetString("UI_Desc_CheckingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find and select the &quot;StarCitizen&quot; folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Desc_ChooseStarCItizenFolder {
            get {
                return ResourceManager.GetString("UI_Desc_ChooseStarCItizenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder directory by &apos;Edit&apos; button과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Desc_ChooseStarCItizenFolderBtn {
            get {
                return ResourceManager.GetString("UI_Desc_ChooseStarCItizenFolderBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ex) C:\Programe Files\Roberts Space Industries\StarCitizen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Desc_ChooseStarCitizenFolerExample {
            get {
                return ResourceManager.GetString("UI_Desc_ChooseStarCitizenFolerExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installation complete.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Desc_InstallationComplete {
            get {
                return ResourceManager.GetString("UI_Desc_InstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Desc_LocailzationInstaling {
            get {
                return ResourceManager.GetString("UI_Desc_LocailzationInstaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **Cannot found document.**과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Desc_NotFoundMarkdown {
            get {
                return ResourceManager.GetString("UI_Desc_NotFoundMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Localization Version.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Desc_SelectLocalizationVersion {
            get {
                return ResourceManager.GetString("UI_Desc_SelectLocalizationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **The document cannot be loaded.**과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Desc_UnableMarkdown {
            get {
                return ResourceManager.GetString("UI_Desc_UnableMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating SCTools과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Desc_UpdatingProgram {
            get {
                return ResourceManager.GetString("UI_Desc_UpdatingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAQ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Tab_Main_Qna {
            get {
                return ResourceManager.GetString("UI_Tab_Main_Qna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Releases과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Tab_Main_ReleaseNote {
            get {
                return ResourceManager.GetString("UI_Tab_Main_ReleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Localization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Title_ChooseLocalization {
            get {
                return ResourceManager.GetString("UI_Title_ChooseLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SCTools과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Title_ProgramTitle {
            get {
                return ResourceManager.GetString("UI_Title_ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   01과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Title_Step_01 {
            get {
                return ResourceManager.GetString("UI_Title_Step_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   02과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Title_Step_02 {
            get {
                return ResourceManager.GetString("UI_Title_Step_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   03과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Title_Step_03 {
            get {
                return ResourceManager.GetString("UI_Title_Step_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @echo off
        ///
        ///set workpath=%~dp0
        ///set updatepath=%workpath%updates\
        ///set latestpath=%updatepath%latest\
        ///
        ///timeout 1
        ///xcopy &quot;%latestpath%*.*&quot; &quot;%workpath%&quot; /s /k /h /y
        ///if not errorlevel 0 goto update_error
        ///
        ///del &quot;%updatepath%latest.json&quot;
        ///del &quot;%updatepath%latest.zip&quot;
        ///del /q &quot;%latestpath%*&quot;
        ///for /d %%p in (&quot;%latestpath%*.*&quot;) do rmdir /s /q &quot;%%p&quot;
        ///rmdir /s /q &quot;%latestpath%&quot;
        ///
        ///start &quot;&quot; &quot;%workpath%SCTool_Redesigned.exe&quot; update_status 0
        ///exit
        ///
        ///:update_error
        ///
        ///start &quot;&quot; &quot;%workpath%SCTool_Redesigned.exe&quot; updat[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateScript {
            get {
                return ResourceManager.GetString("UpdateScript", resourceCulture);
            }
        }
    }
}
