name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # - name: Setup msbuild
      #   uses: microsoft/setup-msbuild@v1.0.2
      #   with:
      #     vs-version: '[16.5,16.6)'

      - name: Setup nuget
        uses: nuget/setup-nuget@v1
        

          
      - name: Build app
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
          .\MSBuild.exe D:\a\Shatagon\Shatagon\SCTools\SCTools.sln /t:restore /t:SCTool_Redesigned /p:Configuration=Release /p:Platform="Any CPU" /p:RestorePackagesConfig=true -m
          cd "D:\a\Shatagon\Shatago"
        
      - name: Compress component
        uses: papeloto/action-zip@v1
        with:
          files: SCTools\SCTool_Redesigned\bin\Release
          dest: Release.zip
      
      - name: Delete tag and release
        uses: dev-drprasad/delete-tag-and-release@v0.1.3
        with:
          delete_release: true
          tag_name: dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Release.zip
          asset_name: Release.zip
          tag: dev
          prerelease: true
          overwrite: true
          body: "Warning: This is the development version. You may encounter 30K errors!"
