name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup nuget
        uses: nuget/setup-nuget@v1
        
      #- name: Restore nuget packages
      #  run: nuget restore SCTools\SCTools.sln -PackagesDirectory SCTool_Redesigned
          
      - name: Build app
        run: msbuild SCTools\SCTools.sln /t:restore /t:SCTool_Redesigned /p:Configuration=Release /p:Platform="Any CPU" /p:RestorePackagesConfig=true
      
      - name: Compress component
        uses: papeloto/action-zip@v1
        with:
          files: SCTools\SCTool_Redesigned\bin\Release
          dest: latest.zip
      
      - name: Create release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: latest.zip
          asset_name: latest.zip
          tag: latest
          overwrite: true
          body: This is the latest version.
      
